#! /usr/bin/env bash

set -euxo pipefail

REPOROOT=$(git rev-parse --show-toplevel)

pushd "$REPOROOT"
npins update
# Nix doesn't seem to detect that the sources.json file has changed
echo "# Pins updated at $(date --iso-8601=seconds)" >>npins/default.nix
nix-build shell.nix
popd

set +x
echo "Finished updating pins. Remember to run 'home-manager switch' or 'nixos-rebuild switch'."
